import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./components/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#777871",
        "on-secondary": "#ffffff",
        "secondary": "#4c56af",
        "tertiary": "#5f5e5e",
        "secondary-fixed-dim": "#bdc2ff",
        "primary-fixed-dim": "#ffb4ac",
        "tertiary-container": "#f7f4f4",
        "surface-container-low": "#f5f3ee",
        "on-secondary-fixed": "#000767",
        "on-tertiary-container": "#706f6f",
        "outline-variant": "#c7c7bf",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "on-surface": "#1b1c19",
        "surface-container-highest": "#e4e2dd",
        "secondary-container": "#959efd",
        "inverse-surface": "#30312e",
        "surface-dim": "#dbdad5",
        "on-tertiary-fixed": "#1b1c1c",
        "inverse-primary": "#ffb4ac",
        "background": "#fbf9f4",
        "on-surface-variant": "#464742",
        "tertiary-fixed": "#e5e2e1",
        "surface-tint": "#b91d20",
        "on-error": "#ffffff",
        "on-secondary-container": "#27308a",
        "on-background": "#1b1c19",
        "surface-variant": "#e4e2dd",
        "on-primary-container": "#d2312f",
        "primary": "#b91d20",
        "surface-container-high": "#eae8e3",
        "on-secondary-fixed-variant": "#343d96",
        "secondary-fixed": "#e0e0ff",
        "primary-container": "#fff2f1",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "surface-container": "#f0eee9",
        "surface": "#fbf9f4",
        "on-tertiary-fixed-variant": "#474746",
        "on-primary": "#ffffff",
        "surface-bright": "#fbf9f4",
        "inverse-on-surface": "#f2f1ec",
        "primary-fixed": "#ffdad6",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#410003",
        "on-primary-fixed-variant": "#93000e",
      },
      fontFamily: {
        "headline": ["var(--font-manrope)", "sans-serif"],
        "body": ["var(--font-manrope)", "sans-serif"],
        "label": ["var(--font-inter)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};

export default config;
